### PR TITLE
Fix misplaced static_assert

### PR DESCRIPTION
**Pull request by jgopel**

### CODE REVIEW

**Comment by jgopel** [comment]
Given the wording of this `static_assert()` and what I've understood of the docs, I thought it made sense to relocate this to `sep`. If that's not the case, I propose rewording the message. I'd be happy to write that rewording if that's a change that would be accepted.

**Comment by foonathan** [comment]
It's the mssage that's wrong, not the placement, yes.

`list(foo, dsl::sep(...))` does *not* require the branch condition `list(foo, dsl::trailng_sep(...))` does. So maybe just change `without` -> `with`?

**Comment by jgopel** [comment]
Updated! Thanks for the feedback.

**Comment by foonathan** [comment]
Thanks.

**Pull request merged**
