### PR TITLE
ensure lexy::_detail::lazy_init selects the correct storage

### PR DESCRIPTION
**Pull request by Ryan-rsm-McKenzie**
See this [godbolt](https://godbolt.org/z/zcjG6E) link for why this is even necessary.

### CODE REVIEW

**Comment by foonathan** [comment]
That seems like an MSVC bug: https://godbolt.org/z/cqqec1

Can you please add a comment to indicate that this is a compiler workaround and verify whether the same logic should apply to `lexy::result`? Thanks.

**Comment by Ryan-rsm-McKenzie** [comment]
I managed to get a better repro:
https://godbolt.org/z/Y1h7a8

**Comment by Ryan-rsm-McKenzie** [comment]
It's probably better to check `is_trivially_move_constructible`, `is_trivially_move_assignable`, and `is_trivially_destructible` since that's what you actually use.

**Comment by foonathan** [comment]
> It's probably better to check is_trivially_move_constructible, is_trivially_move_assignable, and is_trivially_destructible since that's what you actually use.

And a type is `std::is_trivially_copyable` if and only if all special members are trivial: https://en.cppreference.com/w/cpp/types/is_trivially_copyable
This is not to be confused with `std::is_trivially_copy_constructible` which checks only the copy constructor.

So `std::is_trivially_copyable` implies `is_trivially_[move/copy]_[constructible/assignable]` and `is_trivially_destructible`. That it doesn't in your first godbolt link, seems like a compiler bug. The second one is more interesting

**Comment by foonathan** [comment]
Ah, I found something about your second example: https://godbolt.org/z/5dv5aM

The type isn't `is_trivially_[move/copy]_assignable` because it isn't assignable. The weird templated operators aren't copy/move assignment operators.

**Comment by foonathan** [comment]
So what is your underlying issue here exactly? That `lazy_init<std::pair<std::string_view, std::string_view>>` doesn't work, for some definition of work?

**Comment by Ryan-rsm-McKenzie** [comment]
Here's a new [godbolt](https://godbolt.org/z/TfEd3K) example to show that MSVC and GCC agree it's not a fluke. The first example with pair I posted doesn't work with GCC because it's unique to the MS STL which implements pair [using this trick](https://github.com/microsoft/STL/blob/main/stl/inc/utility#L282). I used `std::pair<std::string_view, std::string_view>` because I lifted it straight from my code base, as `lazy_init` was failing on it.

**Comment by foonathan** [comment]
What is the error message you're getting when using pair with lazy_init?

**Comment by Ryan-rsm-McKenzie** [comment]
I'm getting this: https://godbolt.org/z/n465Mz

**Comment by Ryan-rsm-McKenzie** [comment]
Note that clang does not believe that `foo` satisfies `is_trivially_copyable`, which seems to be related to https://reviews.llvm.org/D86126 which has a good discussion on the implications of the type trait.

**Comment by foonathan** [comment]
Okay, the behavior is definitely weird: https://godbolt.org/z/T66rPf

I agree that this is a good workaround for now:

> It's probably better to check is_trivially_move_constructible, is_trivially_move_assignable, and is_trivially_destructible since that's what you actually use.

Please apply it here and to `lexy::result` with a comment linking back to this issue. Can you also add a test with a move-only type?

**Comment by Ryan-rsm-McKenzie** [comment]
Both `lazy_init` and `result` use private inheritance so the move constructor/assignment operators are hidden:
https://github.com/foonathan/lexy/blob/12eff6965009e1c281ae3d9cca6255f78cdc32f4/include/lexy/_detail/lazy_init.hpp#L90
https://github.com/foonathan/lexy/blob/12eff6965009e1c281ae3d9cca6255f78cdc32f4/include/lexy/result.hpp#L149
The only place they actually get invoked is here:
https://github.com/foonathan/lexy/blob/12eff6965009e1c281ae3d9cca6255f78cdc32f4/include/lexy/_detail/lazy_init.hpp#L102
I don't know if this was intentional, but you could probably use this fact to simplify the implementation.

**Comment by foonathan** [comment]
They're also used when trying to copy/move a result/lazy_init.

**Comment by Ryan-rsm-McKenzie** [comment]
Oh, I thought default access was depended on the derived class's type, but it's actually dependent on the base class's type. Today I learned.

**Comment by foonathan** [comment]
No, they do use private inheritance. But as result has no move constructor on its own, the compiler geneates one that calls the base class version etc

**Comment by Ryan-rsm-McKenzie** [comment]
I am learning many things about special member functions in this pr.

**Comment by Ryan-rsm-McKenzie** [comment]
> Can you also add a test with a move-only type?

Could you explain what you mean by a move only type?

**Comment by foonathan** [comment]
> > Can you also add a test with a move-only type?
> 
> Could you explain what you mean by a move only type?

I meant adding a test for something like `std::unique_ptr<int>`, but that's not actually necessary. Thanks for the PR.

**Comment by foonathan** [comment]
FYI: https://foonathan.net/2021/03/trivially-copyable/

**Pull request merged**
